/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fundraising_Application;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author floss
 */
public class Deposit extends javax.swing.JFrame {
    
    ArrayList <CustomerState> CustomerState;
     ArrayList <CustomerAccount> Customers;

    /**
     * Creates new form Withdraw
     */
    public Deposit() {
        initComponents();
        CustomerState = new ArrayList<CustomerState>();
        Customers = new ArrayList<CustomerAccount>();
        RetriveCustomerState();
    }
    
    
    public void saveCustomersToFile(){
         
            try 
            {
              FileOutputStream file = new FileOutputStream("src\\DataBase\\Cutomers.dat");
              ObjectOutputStream outputFile = new ObjectOutputStream(file);
                
              
              for (int i=0; i<Customers.size(); i++){
                  
                  outputFile.writeObject(Customers.get(i));
                  
              }
              
              outputFile.close();
              
             
              
  
             
            }
        
         catch (IOException e){
            
          //  JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
        
    }
    
    
    public void RetriveCustomerState()
    {
        try
        {
        
            FileInputStream file = new FileInputStream("src\\DataBase\\CustomerState.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);
        boolean EndOfFile = false;
        
        while (!EndOfFile){
            
            try 
            {
              CustomerState.add((CustomerState) inputFile.readObject());
                
            }
            catch (EOFException e)
            {
                EndOfFile = true;
            }
            catch (Exception d)
            {
             //JOptionPane.showMessageDialog(null, d.getMessage());
            }
        }
        
        inputFile.close();
        }
        catch (IOException l){
            
            //JOptionPane.showMessageDialog(null, l.getMessage());
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Deposit Amount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 170, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fundraising_Application/logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jTextField1.setText("0");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 170, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 330, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Please specify the amount you wish to Deposit into your account");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 430, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        String z = CustomerState.get(0).CurrentCustomerState;
        String y[] = z.split(" ");
        
        
        try
        {
        
        FileInputStream file = new FileInputStream("src\\DataBase\\Cutomers.dat");
        ObjectInputStream inputFile = new ObjectInputStream(file);
        boolean endOfFile = false;
        
        while (!endOfFile){
            
            try 
            {
              Customers.add((CustomerAccount) inputFile.readObject());
                
            }
            catch (EOFException e)
            {
                endOfFile = true;
            }
            catch (Exception f)
            {
             //JOptionPane.showMessageDialog(null, f.getMessage());
            }
        }
        
        inputFile.close();
        }
        
        catch (IOException e){
            
          //  JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
        
        
        
        
        
        
        
        
        if(jTextField1.getText().isEmpty() ){
            
                         JOptionPane.showMessageDialog(null, "One of the Required fields is empty please fill it");

 }else{
            
           
      
   boolean abort = false;    
   
   boolean Match = false;
           
           
   for (int i=0;i<Customers.size() && !abort ;i++) {
           
          
     
      if (y[0].equals(Customers.get(i).getName().trim())  && y[1].equals(Customers.get(i).getPassword()) ){
              
          
          
          
                    
                     Customers.get(i).Balance += Integer.parseInt (jTextField1.getText());
                     jTextArea1.append(" ######## INVOICE ####### " + "\n");
                     jTextArea1.append(" National Bank Of Egypt " + "\n");
                     jTextArea1.append(" You have Deposited " + jTextField1.getText() + "\n" );
                     jTextArea1.append(" From your account Number " + "\n" );
                     jTextArea1.append( " " + Customers.get(i).getAccountNumber() + "\n" );
                     int currentBalanceAfterDepsoit = Customers.get(i).Balance;
                     jTextArea1.append(" You current Blance is " + String.valueOf(currentBalanceAfterDepsoit) + "\n");
                     jTextArea1.append(" If you faced any problem, " + "\n");
                     jTextArea1.append(" please call our customer service, " + "\n"); 
                     jTextArea1.append(" PHONE NUMBER : 01025369874 " + "\n");
                     jTextArea1.append(" Thank you for choosing us " + "\n");
                     jTextArea1.append( "\n");
                     
                     
                    System.out.print(Customers.get(i).Balance);
                    System.out.print(Customers.get(i).Name);
                     
                     
                     saveCustomersToFile();
                     
                     
                     
          }
                     
                
      }
   
     
   
   
    
        }  
        
        
        
        
        
  
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
