/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fundraising_Application;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author JhonsonTheGreat
 */
public class Donate_Via_Credit_Card extends javax.swing.JFrame {
     ArrayList <VolunteerState> Vstate;
     ArrayList <RegisteredDoner> Customers;
     ArrayList <CustomerState> CustomerState;

    /**
     * Creates new form Withdraw
     */
    public Donate_Via_Credit_Card() {
        initComponents();
        Vstate = new ArrayList<VolunteerState>();
        Customers = new ArrayList<RegisteredDoner>();
        CustomerState = new ArrayList<CustomerState>();
        RetriveCustomerState();
    }

    
    
    public void saveCustomersToFile(){
         
            try 
            {
              FileOutputStream file = new FileOutputStream("src\\DataBase\\Cutomers.dat");
              ObjectOutputStream outputFile = new ObjectOutputStream(file);
                
              
              for (int i=0; i<Customers.size(); i++){
                  
                  outputFile.writeObject(Customers.get(i));
                  
              }
              
              outputFile.close();
              
              
  
             
            }
        
         catch (IOException e){
            
           // JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
        
    }
    
    
    public void RetriveCustomerState()
    {
        try
        {
        
            FileInputStream file = new FileInputStream("src\\DataBase\\CustomerState.dat");
            ObjectInputStream inputFile = new ObjectInputStream(file);
        boolean EndOfFile = false;
        
        while (!EndOfFile){
            
            try 
            {
              CustomerState.add((CustomerState) inputFile.readObject());
                
            }
            catch (EOFException e)
            {
                EndOfFile = true;
            }
            catch (Exception d)
            {
             //JOptionPane.showMessageDialog(null, d.getMessage());
            }
        }
        
        inputFile.close();
        }
        catch (IOException l){
            
           // JOptionPane.showMessageDialog(null, l.getMessage());
            
        }
        
        
    }
    /**
     * Creates new form Donate_Via_Credit_Card
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        acctextfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Donate Via Credit Card");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(830, 450));
        setPreferredSize(new java.awt.Dimension(830, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Donate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 120, 30));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 420, 190));

        acctextfield.setText("e.g: XXXX-XXXX-XXXX-XXXX");
        getContentPane().add(acctextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 210, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 310, 380));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Credit Card Type");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 210, 20));

        jTextField2.setText("0");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 120, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Credit Card Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 170, 20));

        jRadioButton1.setText("Master Card");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jRadioButton2.setText("Visa");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Amount to Donate");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 140, -1));

        jTextField1.setToolTipText("");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Card Holder Full Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CVV");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 130, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 120, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 420, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
                    String z = CustomerState.get(0).CurrentCustomerState;
                    String y[] = z.split(" ");
                    String UserName = y[0];
                    String PassWord = y[1];
                    
                    
                    
                    
                    try {
            
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/registered_doner","root", "1234567890");
            
            
            
                        PreparedStatement st = (PreparedStatement) connection.prepareStatement("Select * from registered_doner where Username=? and Password=?");
                        st.setString(1, UserName);
                        st.setString(2, PassWord);
                        ResultSet rs = st.executeQuery();
            
            
            
                    if (rs.next()){
                
                        String id = String.valueOf(rs.getInt("ID"));
                        String username = rs.getString("Username");
                        String Password = rs.getString("Password");
                        String Email = rs.getString("Email");
                        String Phone_number = rs.getString("Phone_number");
                        String Address = rs.getString("Address");
                        String Credit_Card_Number = rs.getString("Credit_Card_Number");
                        String Bank_Account_Number = rs.getString("Bank_Account_Number");
                        
                        jTextArea1.append(" ######## INVOICE ####### " + "\n");
                        jTextArea1.append(" Thank you for your donation Mr." + username + "\n");
                        jTextArea1.append(" We sent you a confirmation letter for your Donation " + "\n");
                        jTextArea1.append(" On your email address " + Email + "\n");
                        jTextArea1.append(" SMS confirmation was sent to " + Phone_number + "\n");
                        jTextArea1.append(" National Bank Of Egypt " + "\n");
                        jTextArea1.append(" You have Deposited " + jTextField2.getText() + "\n" );
                        jTextArea1.append(" From your CreditCard Number " + "\n" );
                        jTextArea1.append( " " + acctextfield.getText() + "\n" );
                        jTextArea1.append(" If you faced any problem, " + "\n");
                        jTextArea1.append(" please call our customer service, " + "\n"); 
                        jTextArea1.append(" PHONE NUMBER : 01025369874 " + "\n");
                        jTextArea1.append(" Thank you for Donating to us " + "\n");
                        jTextArea1.append( "\n");
                     
                        
                        }
                    }
                    catch (Exception e){
            
                     System.out.println(e.getMessage());
            
                    }
                    
                    
      
                    
                    
       

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donate_Via_Credit_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donate_Via_Credit_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donate_Via_Credit_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donate_Via_Credit_Card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donate_Via_Credit_Card().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acctextfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
